apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: c30y7l29h-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: c30y7l29h-go 
  name: c30y7l29h-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: c30y7l29h-go 
